fix: EADDRINUSE: address already in use - when a stale SOCKET_PATH file already exists (#15449)
Occasionally socket file is not removed when server crashes/shutdown.
This patch attempts to delete the file before restarting the server.
Applies similar solution as was pulled into *adapter-deno* package
recently:

https://github.com/NextLegacy/sveltekit-adapter-deno
https://github.com/NextLegacy/sveltekit-adapter-deno/pull/1
https://github.com/NextLegacy/sveltekit-adapter-deno/pull/2

To reproduce, create a sock file, and attempt to start the server:

```
> node -r dotenv/config index.js
node:events:486
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use /var/home/.../app/.run/stage.sock
    at Server.setupListenHandle [as _listen2] (node:net:1994:21)
    at listenInCluster (node:net:2073:12)
    at Server.listen (node:net:2195:5)
    at Polka.listen (file:///var/home/.../app/stage/index.js:206:22)
    at file:///var/home/.../app/stage/index.js:310:9
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:2052:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '/var/home/.../app/.run/stage.sock',
  port: -1
}
```

After adding this patch, starting the server succeeds:

```
> node -r dotenv/config index.js
Listening on /var/home/.../app/.run/stage.sock
```

---

### Please don't delete this checklist! Before submitting the PR, please
make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is
discussed ahead of time. In many cases, features are absent for a
reason. For large changes, please create an RFC:
https://github.com/sveltejs/rfcs
- [*] This message body should clearly illustrate what problems it
solves.
- [*] Ideally, include a test that fails without this PR but passes with
it.

### Tests
- [*] Run the tests with `pnpm test` and lint the project with `pnpm
lint` and `pnpm check`

### Changesets
- [ ] If your PR makes a change that should be noted in one or more
packages' changelogs, generate a changeset by running `pnpm changeset`
and following the prompts. Changesets that add features should be
`minor` and those that fix bugs should be `patch`. Please prefix
changeset messages with `feat:`, `fix:`, or `chore:`.

### Edits

- [*] Please ensure that 'Allow edits from maintainers' is checked. PRs
without this option may be closed.

---------

Co-authored-by: Tee Ming <chewteeming01@gmail.com>
Co-authored-by: Rich Harris <richard.a.harris@gmail.com>
Co-authored-by: Rich Harris <rich.harris@vercel.com>
Co-authored-by: Rich Harris <hello@rich-harris.dev>